version: "3.9"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/postgres-data:/var/lib/postgresql/data

  python-django:
    build: .
    restart: always
    depends_on: 
      - db
    env_file: 
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/api    
    command: ["./wait-for-it.sh", "db:5432", "--", "./init.sh"]