# Generated by Django 3.2.5 on 2021-07-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
