# Generated by Django 3.2.5 on 2021-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_app', '0003_rename_pubcic_id_user_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
