# Generated by Django 3.2.5 on 2021-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_app', '0004_alter_user_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvote_amount',
            field=models.IntegerField(default=0),
        ),
    ]
